// Tactic: Credential Access | Techniques: T1555/T1552 Credentials from Web Browsers / Unsecured Credentials
DeviceProcessEvents
//| where Timestamp > ago(lookback)
| where FileName in~ ("cmdkey.exe","vaultcmd.exe","reg.exe","rundll32.exe")
   or ProcessCommandLine has_any ("Login Data","/list","/export","/decode","DPAPI","SAM","SYSTEM","SECURITY")
| project Timestamp, DeviceName, FileName, ProcessCommandLine
